### ISSUE TITLE
Chunks appear out of order

### ISSUE THREAD

**Issue by rdmcgregor** [chen-ye/hubot-chunkify#3] opened 2016-08-13 11:12 UTC
Chunks appear out of sequence, and apparently in random order.

This is witnessed when used with `hubot-fb` adapter.  Not tested with any other adapter.

Example is when a hubot responds with the laws of robotics, they display out of sequence.

**Comment by TobiTenno** [comment] 2016-09-09 16:45
I think the problem is that it also chunks messages per-line with that, too. I proposed a fix for some of it in #2, but I don't know if it fixes the out-of-order issues. the problem for that is that, since coffee and javascript are async, and depending on how your adapter sends messages, it could cause different messages to send "faster".

**Comment by chen-ye** [comment] 2016-09-20 18:13
fixed in https://github.com/chen-ye/hubot-fb/pull/12 for `hubot-fb`

**Closed as completed by chen-ye** 2016-09-20 18:13 UTC

**Comment by TobiTenno** [comment] 2016-09-20 18:18
hmmm, did it get committed here too?

**Comment by chen-ye** [comment] 2016-09-20 18:22
The problem was on the adapter side. No changes should be required for `hubot-chunkify`.   (of course, you'll need to use an adapter that supports ordered message sending, but it's better to implement that on the adapter than in chunkify)
